/* GENERATED by tools/build-data.mjs from /data/*.csv. DO NOT EDIT BY HAND. */
/* Edit the CSVs in /data, then run: node tools/build-data.mjs */
const TUBES = {
  "bc_aerobic": {
    "name": "Blood Culture, Aerobic",
    "color": "#3b82f6",
    "draw": 1,
    "ml": 10,
    "additive": "Aerobic culture medium",
    "note": "Aseptic technique. Fill to the mark. Collect BEFORE the anaerobic bottle."
  },
  "bc_anaerobic": {
    "name": "Blood Culture, Anaerobic",
    "color": "#f97316",
    "draw": 2,
    "ml": 10,
    "additive": "Anaerobic culture medium",
    "note": "Collect AFTER the aerobic bottle."
  },
  "blue": {
    "name": "Light Blue (Sodium Citrate)",
    "color": "#60a5fa",
    "draw": 3,
    "ml": 2.7,
    "additive": "3.2% sodium citrate, coagulation",
    "note": "Fill exactly to the line, the blood:anticoagulant ratio is critical.",
    "maxTests": 5
  },
  "gold": {
    "name": "Gold / SST (Serum)",
    "color": "#d4af37",
    "draw": 4,
    "ml": 5,
    "additive": "Clot activator + separator gel, serum",
    "note": "",
    "maxTests": 15
  },
  "green": {
    "name": "Green (Lithium Heparin)",
    "color": "#34d399",
    "draw": 5,
    "ml": 4,
    "additive": "Lithium heparin, plasma",
    "note": "",
    "maxTests": 15
  },
  "purple": {
    "name": "Purple / Lavender (EDTA)",
    "color": "#a78bfa",
    "draw": 6,
    "ml": 4,
    "additive": "EDTA anticoagulant, whole blood",
    "note": "",
    "maxTests": 12
  },
  "pink": {
    "name": "Pink (EDTA, Blood Bank)",
    "color": "#f472b6",
    "draw": 7,
    "ml": 6,
    "additive": "EDTA, group & hold / crossmatch",
    "note": "Strict patient-ID and labelling rules apply for transfusion samples."
  },
  "grey": {
    "name": "Grey (Fluoride Oxalate)",
    "color": "#9ca3af",
    "draw": 8,
    "ml": 2,
    "additive": "Sodium fluoride / potassium oxalate, glycolysis inhibitor",
    "note": "",
    "maxTests": 8
  },
  "royalblue": {
    "name": "Royal Blue (Trace Elements)",
    "color": "#1d4ed8",
    "draw": 9,
    "ml": 6,
    "additive": "Trace-element-free tube",
    "note": "Draw-order position for trace-element tubes varies, check local policy.",
    "maxTests": 6
  }
};
const TESTS = [
  {
    "name": "Full Blood Count",
    "tube": "purple",
    "aliases": [
      "FBC",
      "FBE",
      "CBC",
      "full blood exam",
      "complete blood count",
      "blood count"
    ],
    "offsite": "none",
    "short": "FBC",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/F/Full-Blood-Count"
    }
  },
  {
    "name": "White Cell Count",
    "tube": "purple",
    "aliases": [
      "WCC",
      "white cell count",
      "white blood cells"
    ],
    "offsite": "none",
    "short": "WCC",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/W/White-Cell-Count"
    }
  },
  {
    "name": "Platelet Count",
    "tube": "purple",
    "aliases": [
      "platelets",
      "PLT",
      "platelet count"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Platelet-Count"
    }
  },
  {
    "name": "Blood Film",
    "tube": "purple",
    "aliases": [
      "film",
      "blood film",
      "peripheral smear"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/B/Blood-Film"
    }
  },
  {
    "name": "Reticulocyte count",
    "tube": "purple",
    "aliases": [
      "Reticulocytes",
      "retics"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/R/Reticulocyte-count"
    }
  },
  {
    "name": "Erythrocyte sedimentation rate",
    "tube": "purple",
    "aliases": [
      "ESR",
      "sed rate"
    ],
    "offsite": "none",
    "short": "ESR",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/E/Erythrocyte-sedimentation-rate"
    }
  },
  {
    "name": "HbA1c",
    "tube": "purple",
    "aliases": [
      "glycated haemoglobin",
      "glycated hemoglobin",
      "glycosylated haemoglobin",
      "hba1c"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/H/HbA1c"
    }
  },
  {
    "name": "Direct antiglobulin test",
    "tube": "purple",
    "aliases": [
      "Coombs / DCT",
      "coombs",
      "direct coombs",
      "DCT"
    ],
    "offsite": "none",
    "short": "DCT",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/D/Direct-antiglobulin-test"
    }
  },
  {
    "name": "Malaria",
    "tube": "purple",
    "aliases": [
      "malaria parasites",
      "thick and thin",
      "malaria film"
    ],
    "offsite": "none"
  },
  {
    "name": "Haemochromatosis (HFE)",
    "tube": "purple",
    "aliases": [
      "haemochromatosis",
      "HFE",
      "hereditary haemochromatosis"
    ],
    "offsite": "usually"
  },
  {
    "name": "Thalassaemia",
    "tube": "purple",
    "aliases": [
      "thalassaemia",
      "thalassemia"
    ],
    "offsite": "usually"
  },
  {
    "name": "Parathyroid Hormone",
    "tube": "purple",
    "aliases": [
      "PTH",
      "parathyroid hormone",
      "parathyroid"
    ],
    "offsite": "maybe",
    "short": "PTH",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Parathyroid-Hormone"
    }
  },
  {
    "name": "Homocysteine",
    "tube": "purple",
    "aliases": [
      "homocysteine"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/H/Homocysteine"
    }
  },
  {
    "name": "Cyclosporin",
    "tube": "purple",
    "aliases": [
      "Ciclosporin",
      "cyclosporine"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Cyclosporin"
    }
  },
  {
    "name": "Tacrolimus",
    "tube": "purple",
    "aliases": [
      "tacrolimus",
      "FK506"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/T/Tacrolimus"
    }
  },
  {
    "name": "INR",
    "tube": "blue",
    "aliases": [
      "INR",
      "international normalised ratio"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/I/INR"
    }
  },
  {
    "name": "APTT",
    "tube": "blue",
    "aliases": [
      "APTT",
      "aptt",
      "activated partial thromboplastin time"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/APTT"
    }
  },
  {
    "name": "Prothrombin Time",
    "tube": "blue",
    "aliases": [
      "PT",
      "prothrombin",
      "prothrombin time"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Prothrombin-Time"
    }
  },
  {
    "name": "Coagulation Profile",
    "tube": "blue",
    "aliases": [
      "coags",
      "coag",
      "coagulation profile",
      "clotting screen",
      "coagulation screen"
    ],
    "offsite": "none",
    "short": "Coags",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Coagulation-Profile"
    }
  },
  {
    "name": "D-Dimer",
    "tube": "blue",
    "aliases": [
      "d-dimer",
      "ddimer",
      "d dimer"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/D/D-Dimer"
    }
  },
  {
    "name": "Fibrinogen",
    "tube": "blue",
    "aliases": [
      "fibrinogen"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/F/Fibrinogen"
    }
  },
  {
    "name": "Factor Assay",
    "tube": "blue",
    "aliases": [
      "factor assay",
      "factor V",
      "factor VIII",
      "factor IX"
    ],
    "offsite": "usually"
  },
  {
    "name": "Lupus Anticoagulant",
    "tube": "blue",
    "aliases": [
      "lupus anticoagulant"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Lupus-Anticoagulant"
    }
  },
  {
    "name": "Anti-Xa",
    "tube": "blue",
    "aliases": [
      "anti-xa",
      "antixa",
      "heparin assay",
      "heparin level"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Group & Hold",
    "tube": "pink",
    "aliases": [
      "group and hold",
      "G&H",
      "group & hold",
      "GH"
    ],
    "offsite": "none"
  },
  {
    "name": "Group & Screen",
    "tube": "pink",
    "aliases": [
      "group and screen",
      "group & screen",
      "type and screen"
    ],
    "offsite": "none"
  },
  {
    "name": "Crossmatch",
    "tube": "pink",
    "aliases": [
      "crossmatch",
      "cross match",
      "XM",
      "GXM"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Crossmatch"
    }
  },
  {
    "name": "Antibody Screen",
    "tube": "pink",
    "aliases": [
      "antibody screen",
      "red cell antibodies"
    ],
    "offsite": "none"
  },
  {
    "name": "Glucose",
    "tube": "grey",
    "aliases": [
      "glucose",
      "BSL",
      "BGL",
      "fasting glucose",
      "random glucose",
      "blood sugar"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/G/Glucose"
    }
  },
  {
    "name": "Oral Glucose Tolerance Test",
    "tube": "grey",
    "aliases": [
      "OGTT",
      "GTT",
      "glucose tolerance test"
    ],
    "offsite": "none",
    "short": "OGTT"
  },
  {
    "name": "Lactate",
    "tube": "grey",
    "aliases": [
      "lactate",
      "lactic acid"
    ],
    "offsite": "none"
  },
  {
    "name": "Zinc",
    "tube": "royalblue",
    "aliases": [
      "zinc",
      "Zn"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/Z/Zinc"
    }
  },
  {
    "name": "Copper",
    "tube": "royalblue",
    "aliases": [
      "copper",
      "Cu"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Copper"
    }
  },
  {
    "name": "Manganese",
    "tube": "royalblue",
    "aliases": [
      "manganese",
      "Mn"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/M/Manganese"
    }
  },
  {
    "name": "Selenium",
    "tube": "royalblue",
    "aliases": [
      "selenium",
      "Se"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/S/Selenium"
    }
  },
  {
    "name": "Trace Elements",
    "tube": "royalblue",
    "aliases": [
      "trace elements",
      "trace metals"
    ],
    "offsite": "usually"
  },
  {
    "name": "Ammonia",
    "tube": "green",
    "aliases": [
      "ammonia",
      "NH3"
    ],
    "offsite": "maybe",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Ammonia"
    }
  },
  {
    "name": "Chromosome Studies",
    "tube": "green",
    "aliases": [
      "chromosome studies",
      "karyotype",
      "cytogenetics"
    ],
    "offsite": "usually"
  },
  {
    "name": "Blood culture",
    "tube": "bc_aerobic",
    "aliases": [
      "Blood Cultures",
      "BC",
      "BCx"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/B/Blood-culture"
    }
  },
  {
    "name": "Urea, Electrolytes & Creatinine",
    "tube": "gold",
    "aliases": [
      "UEC",
      "EUC",
      "U&E",
      "urea",
      "electrolytes",
      "creatinine",
      "renal function",
      "EUCs"
    ],
    "offsite": "none",
    "short": "UEC"
  },
  {
    "name": "eGFR",
    "tube": "gold",
    "aliases": [
      "eGFR",
      "GFR"
    ],
    "offsite": "none"
  },
  {
    "name": "Liver Function Tests",
    "tube": "gold",
    "aliases": [
      "LFT",
      "LFTs",
      "liver function"
    ],
    "offsite": "none",
    "short": "LFT",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Liver-Function-Tests"
    }
  },
  {
    "name": "C-Reactive Protein",
    "tube": "gold",
    "aliases": [
      "CRP",
      "c-reactive protein"
    ],
    "offsite": "none",
    "short": "CRP",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/C-Reactive-Protein"
    }
  },
  {
    "name": "Thyroid Function",
    "tube": "gold",
    "aliases": [
      "TSH",
      "TFT",
      "TFTs",
      "thyroid function",
      "T4",
      "FT4",
      "T3",
      "FT3"
    ],
    "offsite": "none",
    "short": "TFTs"
  },
  {
    "name": "Calcium",
    "tube": "gold",
    "aliases": [
      "calcium",
      "Ca",
      "corrected calcium"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Calcium"
    }
  },
  {
    "name": "Phosphate",
    "tube": "gold",
    "aliases": [
      "phosphate",
      "PO4"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Phosphate"
    }
  },
  {
    "name": "Magnesium",
    "tube": "gold",
    "aliases": [
      "magnesium",
      "Mg"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/M/Magnesium"
    }
  },
  {
    "name": "Urate",
    "tube": "gold",
    "aliases": [
      "urate",
      "uric acid"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/U/Urate"
    }
  },
  {
    "name": "Creatine Kinase",
    "tube": "gold",
    "aliases": [
      "CK",
      "creatine kinase"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Creatine-Kinase"
    }
  },
  {
    "name": "CK-MB",
    "tube": "gold",
    "aliases": [
      "CK-MB",
      "CKMB"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Amylase",
    "tube": "gold",
    "aliases": [
      "amylase"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Amylase"
    }
  },
  {
    "name": "Lipase",
    "tube": "gold",
    "aliases": [
      "lipase"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Lipase"
    }
  },
  {
    "name": "Lipids",
    "tube": "gold",
    "aliases": [
      "lipids",
      "cholesterol",
      "triglycerides",
      "HDL",
      "LDL",
      "lipid profile"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Lipids"
    }
  },
  {
    "name": "Iron Studies",
    "tube": "gold",
    "aliases": [
      "iron studies",
      "iron",
      "transferrin",
      "transferrin saturation"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/I/Iron-Studies"
    }
  },
  {
    "name": "Ferritin",
    "tube": "gold",
    "aliases": [
      "ferritin"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/F/Ferritin"
    }
  },
  {
    "name": "Vitamin B12",
    "tube": "gold",
    "aliases": [
      "B12",
      "vitamin B12",
      "cobalamin"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/V/Vitamin-B12"
    }
  },
  {
    "name": "Folate",
    "tube": "gold",
    "aliases": [
      "folate",
      "folic acid"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/F/Folate"
    }
  },
  {
    "name": "Vitamin D",
    "tube": "gold",
    "aliases": [
      "vitamin D",
      "25-OH vitamin D",
      "25 OH"
    ],
    "offsite": "maybe",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/V/Vitamin-D"
    }
  },
  {
    "name": "Beta-hCG",
    "tube": "gold",
    "aliases": [
      "beta hcg",
      "bhcg",
      "hcg",
      "pregnancy test",
      "quantitative hcg"
    ],
    "offsite": "none"
  },
  {
    "name": "Troponin I",
    "tube": "gold",
    "aliases": [
      "Troponin",
      "trop",
      "troponin T",
      "hs-troponin"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/T/Troponin-I"
    }
  },
  {
    "name": "B-Type natriuretic peptide",
    "tube": "gold",
    "aliases": [
      "BNP / NT-proBNP",
      "BNP",
      "NT-proBNP",
      "nt pro bnp",
      "natriuretic peptide"
    ],
    "offsite": "maybe",
    "short": "BNP",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/B/B-Type-natriuretic-peptide"
    }
  },
  {
    "name": "Procalcitonin",
    "tube": "gold",
    "aliases": [
      "procalcitonin",
      "PCT"
    ],
    "offsite": "maybe",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Procalcitonin"
    }
  },
  {
    "name": "Immunoglobulins",
    "tube": "gold",
    "aliases": [
      "immunoglobulins",
      "IgG",
      "IgA",
      "IgM",
      "IgE"
    ],
    "offsite": "maybe",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/I/Immunoglobulins"
    }
  },
  {
    "name": "Complement (C3/C4)",
    "tube": "gold",
    "aliases": [
      "complement",
      "C3",
      "C4"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Antinuclear Ab",
    "tube": "gold",
    "aliases": [
      "ANA",
      "antinuclear antibody"
    ],
    "offsite": "usually",
    "short": "ANA",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Antinuclear-Ab"
    }
  },
  {
    "name": "Antineutrophil cytoplasmic Ab",
    "tube": "gold",
    "aliases": [
      "ANCA"
    ],
    "offsite": "usually",
    "short": "ANCA",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Antineutrophil-cytoplasmic-Ab"
    }
  },
  {
    "name": "dsDNA",
    "tube": "gold",
    "aliases": [
      "dsDNA",
      "anti-dsDNA",
      "double stranded DNA"
    ],
    "offsite": "usually"
  },
  {
    "name": "Extractable nuclear antigen Ab",
    "tube": "gold",
    "aliases": [
      "ENA",
      "extractable nuclear antigen"
    ],
    "offsite": "usually",
    "short": "ENA",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/E/Extractable-nuclear-antigen-Ab"
    }
  },
  {
    "name": "Rheumatoid Factor",
    "tube": "gold",
    "aliases": [
      "rheumatoid factor",
      "RF"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/R/Rheumatoid-Factor"
    }
  },
  {
    "name": "Cyclic citrullinated peptide Ab",
    "tube": "gold",
    "aliases": [
      "Anti-CCP",
      "CCP"
    ],
    "offsite": "usually",
    "short": "Anti-CCP",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Cyclic-citrullinated-peptide-Ab"
    }
  },
  {
    "name": "Digoxin",
    "tube": "gold",
    "aliases": [
      "digoxin",
      "dig level"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/D/Digoxin"
    }
  },
  {
    "name": "Phenytoin",
    "tube": "gold",
    "aliases": [
      "phenytoin",
      "dilantin"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Phenytoin"
    }
  },
  {
    "name": "Valproate",
    "tube": "gold",
    "aliases": [
      "valproate",
      "sodium valproate",
      "epilim"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/V/Valproate"
    }
  },
  {
    "name": "Carbamazepine",
    "tube": "gold",
    "aliases": [
      "carbamazepine",
      "tegretol"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Carbamazepine"
    }
  },
  {
    "name": "Lithium",
    "tube": "gold",
    "aliases": [
      "lithium",
      "lithium level"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Lithium"
    }
  },
  {
    "name": "Vancomycin",
    "tube": "gold",
    "aliases": [
      "vancomycin",
      "vanc level"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/V/Vancomycin"
    }
  },
  {
    "name": "Gentamicin",
    "tube": "gold",
    "aliases": [
      "gentamicin",
      "gent level"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/G/Gentamicin"
    }
  },
  {
    "name": "Paracetamol",
    "tube": "gold",
    "aliases": [
      "paracetamol",
      "acetaminophen",
      "panadol level"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Paracetamol"
    }
  },
  {
    "name": "Cortisol",
    "tube": "gold",
    "aliases": [
      "cortisol"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Cortisol"
    }
  },
  {
    "name": "Testosterone total",
    "tube": "gold",
    "aliases": [
      "Testosterone"
    ],
    "offsite": "maybe",
    "short": "Testosterone",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/T/Testosterone-Total"
    }
  },
  {
    "name": "Oestradiol",
    "tube": "gold",
    "aliases": [
      "oestradiol",
      "estradiol"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/O/Oestradiol"
    }
  },
  {
    "name": "Progesterone",
    "tube": "gold",
    "aliases": [
      "progesterone"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Progesterone"
    }
  },
  {
    "name": "Prolactin",
    "tube": "gold",
    "aliases": [
      "prolactin"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Prolactin"
    }
  },
  {
    "name": "Follicle stimulating hormone",
    "tube": "gold",
    "aliases": [
      "FSH"
    ],
    "offsite": "none",
    "short": "FSH",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/F/Follicle-stimulating-hormone"
    }
  },
  {
    "name": "Luteinising hormone",
    "tube": "gold",
    "aliases": [
      "LH"
    ],
    "offsite": "none",
    "short": "LH",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Luteinising-hormone"
    }
  },
  {
    "name": "Insulin",
    "tube": "gold",
    "aliases": [
      "insulin"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/I/Insulin"
    }
  },
  {
    "name": "C-Peptide",
    "tube": "gold",
    "aliases": [
      "c-peptide",
      "c peptide"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/C-Peptide"
    }
  },
  {
    "name": "Prostate specific antigen",
    "tube": "gold",
    "aliases": [
      "PSA"
    ],
    "offsite": "none",
    "short": "PSA",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Prostate-specific-antigen"
    }
  },
  {
    "name": "Carcinoembryonic antigen",
    "tube": "gold",
    "aliases": [
      "CEA"
    ],
    "offsite": "none",
    "short": "CEA",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Carcinoembryonic-antigen"
    }
  },
  {
    "name": "CA-125",
    "tube": "gold",
    "aliases": [
      "CA 125",
      "CA-125",
      "ca125"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/CA-125"
    }
  },
  {
    "name": "AFP",
    "tube": "gold",
    "aliases": [
      "AFP",
      "alpha fetoprotein"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/AFP"
    }
  },
  {
    "name": "Coeliac Serology",
    "tube": "gold",
    "aliases": [
      "coeliac",
      "celiac",
      "tTG",
      "gliadin",
      "coeliac serology"
    ],
    "offsite": "maybe"
  },
  {
    "name": "HIV Serology",
    "tube": "gold",
    "aliases": [
      "HIV",
      "hiv serology"
    ],
    "offsite": "maybe",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/H/HIV-Serology"
    }
  },
  {
    "name": "Hepatitis Serology",
    "tube": "gold",
    "aliases": [
      "hepatitis",
      "hep B",
      "hep C",
      "HBsAg",
      "HCV"
    ],
    "offsite": "none"
  },
  {
    "name": "Syphilis Serology",
    "tube": "gold",
    "aliases": [
      "syphilis",
      "RPR",
      "TPHA"
    ],
    "offsite": "maybe",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/S/Syphilis-Serology"
    }
  },
  {
    "name": "Epstein-Barr virus serology",
    "tube": "gold",
    "aliases": [
      "EBV Serology",
      "EBV",
      "epstein barr",
      "monospot"
    ],
    "offsite": "maybe",
    "short": "EBV serology",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/E/Epstein-Barr-virus-serology"
    }
  },
  {
    "name": "CMV Serology",
    "tube": "gold",
    "aliases": [
      "CMV",
      "cytomegalovirus"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Protein Electrophoresis",
    "tube": "gold",
    "aliases": [
      "SPEP",
      "protein electrophoresis",
      "EPP",
      "protein studies"
    ],
    "offsite": "usually",
    "short": "EPG",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/P/Protein-Electrophoresis"
    }
  },
  {
    "name": "Albumin",
    "tube": "gold",
    "aliases": [
      "albumin"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Albumin"
    }
  },
  {
    "name": "Sirolimus",
    "tube": "purple",
    "aliases": [
      "rapamycin",
      "sirolimus level",
      "rapamune"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/S/Sirolimus"
    }
  },
  {
    "name": "Everolimus",
    "tube": "purple",
    "aliases": [
      "everolimus level",
      "certican",
      "afinitor",
      "votubia"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/E/Everolimus"
    }
  },
  {
    "name": "Aldosterone",
    "tube": "gold",
    "aliases": [
      "aldosterone level",
      "aldosterone renin ratio",
      "arr"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Aldosterone"
    }
  },
  {
    "name": "Renin",
    "tube": "purple",
    "aliases": [
      "plasma renin",
      "direct renin",
      "renin activity",
      "pra",
      "renin concentration"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/R/Renin"
    }
  },
  {
    "name": "ACTH",
    "tube": "purple",
    "aliases": [
      "adrenocorticotropic hormone",
      "corticotropin",
      "acth level"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/ACTH"
    }
  },
  {
    "name": "IGF-1",
    "tube": "gold",
    "aliases": [
      "igf1",
      "insulin-like growth factor",
      "somatomedin c"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/I/IGF-1"
    }
  },
  {
    "name": "Growth Hormone",
    "tube": "gold",
    "aliases": [
      "gh level",
      "somatotropin",
      "growth hormone level"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/G/Growth-Hormone"
    }
  },
  {
    "name": "17-hydroxyprogesterone",
    "tube": "gold",
    "aliases": [
      "17-OH-Progesterone",
      "17-ohp",
      "17 hydroxyprogesterone",
      "17-oh progesterone"
    ],
    "offsite": "usually",
    "short": "17-OHP",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/0-9/17-hydroxyprogesterone"
    }
  },
  {
    "name": "Anticardiolipin Antibodies",
    "tube": "gold",
    "aliases": [
      "anticardiolipin",
      "acl antibodies",
      "cardiolipin antibodies"
    ],
    "offsite": "usually"
  },
  {
    "name": "Beta-2 Glycoprotein Antibodies",
    "tube": "gold",
    "aliases": [
      "beta-2 glycoprotein",
      "b2gpi",
      "beta 2 glycoprotein 1"
    ],
    "offsite": "usually"
  },
  {
    "name": "Thyroid Antibodies",
    "tube": "gold",
    "aliases": [
      "anti-tpo",
      "tpo antibodies",
      "thyroid peroxidase antibodies",
      "anti-thyroglobulin",
      "trab",
      "tsh receptor antibodies"
    ],
    "offsite": "usually"
  },
  {
    "name": "Glucose-6-phosphate dehydrogenase",
    "tube": "purple",
    "aliases": [
      "G6PD",
      "g6pd screen"
    ],
    "offsite": "usually",
    "short": "G6PD",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/G/Glucose-6-phosphate-dehydrogenase"
    }
  },
  {
    "name": "JAK2",
    "tube": "purple",
    "aliases": [
      "jak2 v617f",
      "jak2 mutation",
      "jak-2"
    ],
    "offsite": "usually"
  },
  {
    "name": "Cryoglobulins",
    "tube": "gold",
    "aliases": [
      "cryoglobulin",
      "cryoglobulin screen"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Cryoglobulins"
    }
  },
  {
    "name": "Lead",
    "tube": "royalblue",
    "aliases": [
      "blood lead",
      "pb level",
      "lead level"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Lead"
    }
  },
  {
    "name": "Mercury",
    "tube": "royalblue",
    "aliases": [
      "hg level",
      "mercury level"
    ],
    "offsite": "usually"
  },
  {
    "name": "Aluminium",
    "tube": "royalblue",
    "aliases": [
      "aluminum",
      "al level",
      "aluminium level"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Aluminium"
    }
  },
  {
    "name": "Lactate dehydrogenase",
    "tube": "gold",
    "aliases": [
      "LDH",
      "ldh level"
    ],
    "offsite": "none",
    "short": "LDH",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/L/Lactate-dehydrogenase"
    }
  },
  {
    "name": "Osmolality",
    "tube": "gold",
    "aliases": [
      "serum osmolality",
      "plasma osmolality",
      "osmol"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/O/Osmolality"
    }
  },
  {
    "name": "Haptoglobin",
    "tube": "gold",
    "aliases": [
      "hapto"
    ],
    "offsite": "maybe",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/H/Haptoglobin"
    }
  },
  {
    "name": "Ethanol",
    "tube": "gold",
    "aliases": [
      "blood alcohol",
      "alcohol level",
      "etoh",
      "bac"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/E/Ethanol"
    }
  },
  {
    "name": "Salicylate",
    "tube": "gold",
    "aliases": [
      "aspirin level",
      "salicylate level"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/S/Salicylate"
    }
  },
  {
    "name": "Theophylline",
    "tube": "gold",
    "aliases": [
      "theophylline level"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/T/Theophylline"
    }
  },
  {
    "name": "Tobramycin",
    "tube": "gold",
    "aliases": [
      "tobramycin level",
      "tobra"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/T/Tobramycin"
    }
  },
  {
    "name": "Clozapine",
    "tube": "gold",
    "aliases": [
      "clozapine level",
      "norclozapine"
    ],
    "offsite": "none",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Clozapine"
    }
  },
  {
    "name": "SHBG",
    "tube": "gold",
    "aliases": [
      "sex hormone binding globulin"
    ],
    "offsite": "maybe"
  },
  {
    "name": "DHEAS",
    "tube": "gold",
    "aliases": [
      "dhea-s",
      "dhea sulphate",
      "dheas level"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Anti-Mullerian Hormone",
    "tube": "gold",
    "aliases": [
      "amh",
      "anti-mullerian hormone"
    ],
    "offsite": "maybe",
    "short": "AMH",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/A/Anti-Mullerian-Hormone"
    }
  },
  {
    "name": "Beta-2 Microglobulin",
    "tube": "gold",
    "aliases": [
      "b2m",
      "beta 2 microglobulin"
    ],
    "offsite": "usually",
    "short": "B2M",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/B/Beta-2-Microglobulin"
    }
  },
  {
    "name": "Free light chains",
    "tube": "gold",
    "aliases": [
      "Serum Free Light Chains",
      "flc",
      "sflc",
      "kappa lambda ratio"
    ],
    "offsite": "usually",
    "short": "FLC",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/F/Free-light-chains"
    }
  },
  {
    "name": "Immunofixation",
    "tube": "gold",
    "aliases": [
      "ife",
      "immunofixation electrophoresis"
    ],
    "offsite": "usually"
  },
  {
    "name": "Tryptase",
    "tube": "gold",
    "aliases": [
      "mast cell tryptase",
      "serum tryptase"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/T/Tryptase"
    }
  },
  {
    "name": "Caeruloplasmin",
    "tube": "gold",
    "aliases": [
      "ceruloplasmin"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/C/Caeruloplasmin"
    }
  },
  {
    "name": "HLA-B27",
    "tube": "purple",
    "aliases": [
      "hlab27",
      "b27"
    ],
    "offsite": "usually"
  },
  {
    "name": "Vitamin B1",
    "tube": "purple",
    "aliases": [
      "thiamine",
      "thiamine level"
    ],
    "offsite": "usually",
    "sources": {
      "rcpa": "https://www.rcpa.edu.au/Manuals/RCPA-Manual/Pathology-Tests/V/Vitamin-B1"
    }
  }
];
const LABS = [
  {
    "id": "ICPMR",
    "name": "ICPMR Westmead (statewide reference)",
    "state": "NSW"
  },
  {
    "id": "RPA",
    "name": "Royal Prince Alfred (specialised)",
    "state": "NSW"
  },
  {
    "id": "NEPEAN",
    "name": "Nepean Hospital Laboratory",
    "state": "NSW"
  },
  {
    "id": "WESTMEAD",
    "name": "Westmead Hospital Laboratory",
    "state": "NSW"
  }
];
const STATES = [
  {
    "id": "NSW",
    "name": "New South Wales",
    "catalogueHome": "https://catalogue.pathology.health.nsw.gov.au/home",
    "catalogueSearch": "https://catalogue.pathology.health.nsw.gov.au/search?searchValue="
  }
];
const SITES = [
  {
    "id": "default",
    "name": "Generic (NSW default)",
    "state": "NSW",
    "lab": "",
    "region": ""
  },
  {
    "id": "nepean",
    "name": "Nepean Hospital",
    "state": "NSW",
    "lab": "NEPEAN",
    "region": "nbmlhd"
  },
  {
    "id": "westmead",
    "name": "Westmead Hospital",
    "state": "NSW",
    "lab": "WESTMEAD",
    "region": "wslhd"
  }
];
const OVERRIDES = [
  {
    "scope": "site",
    "scopeId": "nepean",
    "test": "Group & Hold",
    "field": "quantity",
    "value": "2"
  }
];
const AVAILABILITY = [
  {
    "test": "Tacrolimus",
    "lab": "ICPMR"
  },
  {
    "test": "Tacrolimus",
    "lab": "WESTMEAD"
  },
  {
    "test": "Cyclosporin",
    "lab": "ICPMR"
  },
  {
    "test": "Antineutrophil cytoplasmic Ab",
    "lab": "RPA"
  },
  {
    "test": "Antineutrophil cytoplasmic Ab",
    "lab": "ICPMR"
  },
  {
    "test": "dsDNA",
    "lab": "RPA"
  },
  {
    "test": "Extractable nuclear antigen Ab",
    "lab": "RPA"
  },
  {
    "test": "Protein Electrophoresis",
    "lab": "ICPMR"
  },
  {
    "test": "Protein Electrophoresis",
    "lab": "WESTMEAD"
  }
];
const REGIONS = [
  {
    "id": "wnswlhd",
    "name": "Western NSW LHD",
    "state": "NSW"
  },
  {
    "id": "nbmlhd",
    "name": "Nepean Blue Mountains LHD",
    "state": "NSW"
  },
  {
    "id": "wslhd",
    "name": "Western Sydney LHD",
    "state": "NSW"
  }
];
const RESOURCES = [
  {
    "level": "national",
    "scope": "",
    "key": "rcpa",
    "label": "RCPA",
    "url": "https://www.rcpa.edu.au/Search-Results?q={q}"
  },
  {
    "level": "state",
    "scope": "NSW",
    "key": "nsw",
    "label": "NSW catalogue",
    "url": "https://catalogue.pathology.health.nsw.gov.au/search?searchValue={q}"
  }
];
