/* GENERATED by tools/build-data.mjs from /data/*.csv. DO NOT EDIT BY HAND. */
/* Edit the CSVs in /data, then run: node tools/build-data.mjs */
const TUBES = {
  "bc_aerobic": {
    "name": "Blood Culture, Aerobic",
    "color": "#3b82f6",
    "draw": 1,
    "ml": 10,
    "additive": "Aerobic culture medium",
    "note": "Aseptic technique. Fill to the mark. Collect BEFORE the anaerobic bottle."
  },
  "bc_anaerobic": {
    "name": "Blood Culture, Anaerobic",
    "color": "#f97316",
    "draw": 2,
    "ml": 10,
    "additive": "Anaerobic culture medium",
    "note": "Collect AFTER the aerobic bottle."
  },
  "blue": {
    "name": "Light Blue (Sodium Citrate)",
    "color": "#60a5fa",
    "draw": 3,
    "ml": 2.7,
    "additive": "3.2% sodium citrate, coagulation",
    "note": "Fill exactly to the line, the blood:anticoagulant ratio is critical.",
    "maxTests": 5
  },
  "gold": {
    "name": "Gold / SST (Serum)",
    "color": "#d4af37",
    "draw": 4,
    "ml": 5,
    "additive": "Clot activator + separator gel, serum",
    "note": "",
    "maxTests": 15
  },
  "green": {
    "name": "Green (Lithium Heparin)",
    "color": "#34d399",
    "draw": 5,
    "ml": 4,
    "additive": "Lithium heparin, plasma",
    "note": "",
    "maxTests": 15
  },
  "purple": {
    "name": "Purple / Lavender (EDTA)",
    "color": "#a78bfa",
    "draw": 6,
    "ml": 4,
    "additive": "EDTA anticoagulant, whole blood",
    "note": "",
    "maxTests": 12
  },
  "pink": {
    "name": "Pink (EDTA, Blood Bank)",
    "color": "#f472b6",
    "draw": 7,
    "ml": 6,
    "additive": "EDTA, group & hold / crossmatch",
    "note": "Strict patient-ID and labelling rules apply for transfusion samples."
  },
  "grey": {
    "name": "Grey (Fluoride Oxalate)",
    "color": "#9ca3af",
    "draw": 8,
    "ml": 2,
    "additive": "Sodium fluoride / potassium oxalate, glycolysis inhibitor",
    "note": "",
    "maxTests": 8
  },
  "royalblue": {
    "name": "Royal Blue (Trace Elements)",
    "color": "#1d4ed8",
    "draw": 9,
    "ml": 6,
    "additive": "Trace-element-free tube",
    "note": "Draw-order position for trace-element tubes varies, check local policy.",
    "maxTests": 6
  }
};
const TESTS = [
  {
    "name": "Full Blood Count",
    "tube": "purple",
    "aliases": [
      "FBC",
      "FBE",
      "CBC",
      "full blood exam",
      "complete blood count",
      "blood count"
    ],
    "offsite": "none"
  },
  {
    "name": "White Cell Count",
    "tube": "purple",
    "aliases": [
      "WCC",
      "white cell count",
      "white blood cells"
    ],
    "offsite": "none"
  },
  {
    "name": "Platelet Count",
    "tube": "purple",
    "aliases": [
      "platelets",
      "PLT",
      "platelet count"
    ],
    "offsite": "none"
  },
  {
    "name": "Blood Film",
    "tube": "purple",
    "aliases": [
      "film",
      "blood film",
      "peripheral smear"
    ],
    "offsite": "none"
  },
  {
    "name": "Reticulocytes",
    "tube": "purple",
    "aliases": [
      "retics",
      "reticulocyte count"
    ],
    "offsite": "none"
  },
  {
    "name": "ESR",
    "tube": "purple",
    "aliases": [
      "erythrocyte sedimentation rate",
      "sed rate"
    ],
    "offsite": "none"
  },
  {
    "name": "HbA1c",
    "tube": "purple",
    "aliases": [
      "glycated haemoglobin",
      "glycated hemoglobin",
      "glycosylated haemoglobin",
      "hba1c"
    ],
    "offsite": "none"
  },
  {
    "name": "Coombs / DCT",
    "tube": "purple",
    "aliases": [
      "coombs",
      "direct coombs",
      "DCT",
      "direct antiglobulin test"
    ],
    "offsite": "none"
  },
  {
    "name": "Malaria",
    "tube": "purple",
    "aliases": [
      "malaria parasites",
      "thick and thin",
      "malaria film"
    ],
    "offsite": "none"
  },
  {
    "name": "Haemochromatosis (HFE)",
    "tube": "purple",
    "aliases": [
      "haemochromatosis",
      "HFE",
      "hereditary haemochromatosis"
    ],
    "offsite": "usually"
  },
  {
    "name": "Thalassaemia",
    "tube": "purple",
    "aliases": [
      "thalassaemia",
      "thalassemia"
    ],
    "offsite": "usually"
  },
  {
    "name": "Parathyroid Hormone",
    "tube": "purple",
    "aliases": [
      "PTH",
      "parathyroid hormone",
      "parathyroid"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Homocysteine",
    "tube": "purple",
    "aliases": [
      "homocysteine"
    ],
    "offsite": "usually"
  },
  {
    "name": "Ciclosporin",
    "tube": "purple",
    "aliases": [
      "ciclosporin",
      "cyclosporin",
      "cyclosporine"
    ],
    "offsite": "usually"
  },
  {
    "name": "Tacrolimus",
    "tube": "purple",
    "aliases": [
      "tacrolimus",
      "FK506"
    ],
    "offsite": "usually"
  },
  {
    "name": "INR",
    "tube": "blue",
    "aliases": [
      "INR",
      "international normalised ratio"
    ],
    "offsite": "none"
  },
  {
    "name": "APTT",
    "tube": "blue",
    "aliases": [
      "APTT",
      "aptt",
      "activated partial thromboplastin time"
    ],
    "offsite": "none"
  },
  {
    "name": "Prothrombin Time",
    "tube": "blue",
    "aliases": [
      "PT",
      "prothrombin",
      "prothrombin time"
    ],
    "offsite": "none"
  },
  {
    "name": "Coagulation Profile",
    "tube": "blue",
    "aliases": [
      "coags",
      "coag",
      "coagulation profile",
      "clotting screen",
      "coagulation screen"
    ],
    "offsite": "none"
  },
  {
    "name": "D-Dimer",
    "tube": "blue",
    "aliases": [
      "d-dimer",
      "ddimer",
      "d dimer"
    ],
    "offsite": "none"
  },
  {
    "name": "Fibrinogen",
    "tube": "blue",
    "aliases": [
      "fibrinogen"
    ],
    "offsite": "none"
  },
  {
    "name": "Factor Assay",
    "tube": "blue",
    "aliases": [
      "factor assay",
      "factor V",
      "factor VIII",
      "factor IX"
    ],
    "offsite": "usually"
  },
  {
    "name": "Lupus Anticoagulant",
    "tube": "blue",
    "aliases": [
      "lupus anticoagulant"
    ],
    "offsite": "usually"
  },
  {
    "name": "Anti-Xa",
    "tube": "blue",
    "aliases": [
      "anti-xa",
      "antixa",
      "heparin assay",
      "heparin level"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Group & Hold",
    "tube": "pink",
    "aliases": [
      "group and hold",
      "G&H",
      "group & hold",
      "GH"
    ],
    "offsite": "none"
  },
  {
    "name": "Group & Screen",
    "tube": "pink",
    "aliases": [
      "group and screen",
      "group & screen",
      "type and screen"
    ],
    "offsite": "none"
  },
  {
    "name": "Crossmatch",
    "tube": "pink",
    "aliases": [
      "crossmatch",
      "cross match",
      "XM",
      "GXM"
    ],
    "offsite": "none"
  },
  {
    "name": "Antibody Screen",
    "tube": "pink",
    "aliases": [
      "antibody screen",
      "red cell antibodies"
    ],
    "offsite": "none"
  },
  {
    "name": "Glucose",
    "tube": "grey",
    "aliases": [
      "glucose",
      "BSL",
      "BGL",
      "fasting glucose",
      "random glucose",
      "blood sugar"
    ],
    "offsite": "none"
  },
  {
    "name": "Oral Glucose Tolerance Test",
    "tube": "grey",
    "aliases": [
      "OGTT",
      "GTT",
      "glucose tolerance test"
    ],
    "offsite": "none"
  },
  {
    "name": "Lactate",
    "tube": "grey",
    "aliases": [
      "lactate",
      "lactic acid"
    ],
    "offsite": "none"
  },
  {
    "name": "Zinc",
    "tube": "royalblue",
    "aliases": [
      "zinc",
      "Zn"
    ],
    "offsite": "usually"
  },
  {
    "name": "Copper",
    "tube": "royalblue",
    "aliases": [
      "copper",
      "Cu"
    ],
    "offsite": "usually"
  },
  {
    "name": "Manganese",
    "tube": "royalblue",
    "aliases": [
      "manganese",
      "Mn"
    ],
    "offsite": "usually"
  },
  {
    "name": "Selenium",
    "tube": "royalblue",
    "aliases": [
      "selenium",
      "Se"
    ],
    "offsite": "usually"
  },
  {
    "name": "Trace Elements",
    "tube": "royalblue",
    "aliases": [
      "trace elements",
      "trace metals"
    ],
    "offsite": "usually"
  },
  {
    "name": "Ammonia",
    "tube": "green",
    "aliases": [
      "ammonia",
      "NH3"
    ],
    "offsite": "none"
  },
  {
    "name": "Chromosome Studies",
    "tube": "green",
    "aliases": [
      "chromosome studies",
      "karyotype",
      "cytogenetics"
    ],
    "offsite": "usually"
  },
  {
    "name": "Blood Cultures",
    "tube": "bc_aerobic",
    "aliases": [
      "blood culture",
      "blood cultures",
      "BC",
      "BCx"
    ],
    "offsite": "none"
  },
  {
    "name": "Urea, Electrolytes & Creatinine",
    "tube": "gold",
    "aliases": [
      "UEC",
      "EUC",
      "U&E",
      "urea",
      "electrolytes",
      "creatinine",
      "renal function",
      "EUCs"
    ],
    "offsite": "none"
  },
  {
    "name": "eGFR",
    "tube": "gold",
    "aliases": [
      "eGFR",
      "GFR"
    ],
    "offsite": "none"
  },
  {
    "name": "Liver Function Tests",
    "tube": "gold",
    "aliases": [
      "LFT",
      "LFTs",
      "liver function"
    ],
    "offsite": "none"
  },
  {
    "name": "C-Reactive Protein",
    "tube": "gold",
    "aliases": [
      "CRP",
      "c-reactive protein"
    ],
    "offsite": "none"
  },
  {
    "name": "Thyroid Function",
    "tube": "gold",
    "aliases": [
      "TSH",
      "TFT",
      "TFTs",
      "thyroid function",
      "T4",
      "FT4",
      "T3",
      "FT3"
    ],
    "offsite": "none"
  },
  {
    "name": "Calcium",
    "tube": "gold",
    "aliases": [
      "calcium",
      "Ca",
      "corrected calcium"
    ],
    "offsite": "none"
  },
  {
    "name": "Phosphate",
    "tube": "gold",
    "aliases": [
      "phosphate",
      "PO4"
    ],
    "offsite": "none"
  },
  {
    "name": "Magnesium",
    "tube": "gold",
    "aliases": [
      "magnesium",
      "Mg"
    ],
    "offsite": "none"
  },
  {
    "name": "Urate",
    "tube": "gold",
    "aliases": [
      "urate",
      "uric acid"
    ],
    "offsite": "none"
  },
  {
    "name": "Creatine Kinase",
    "tube": "gold",
    "aliases": [
      "CK",
      "creatine kinase"
    ],
    "offsite": "none"
  },
  {
    "name": "CK-MB",
    "tube": "gold",
    "aliases": [
      "CK-MB",
      "CKMB"
    ],
    "offsite": "none"
  },
  {
    "name": "Amylase",
    "tube": "gold",
    "aliases": [
      "amylase"
    ],
    "offsite": "none"
  },
  {
    "name": "Lipase",
    "tube": "gold",
    "aliases": [
      "lipase"
    ],
    "offsite": "none"
  },
  {
    "name": "Lipids",
    "tube": "gold",
    "aliases": [
      "lipids",
      "cholesterol",
      "triglycerides",
      "HDL",
      "LDL",
      "lipid profile"
    ],
    "offsite": "none"
  },
  {
    "name": "Iron Studies",
    "tube": "gold",
    "aliases": [
      "iron studies",
      "iron",
      "transferrin",
      "transferrin saturation"
    ],
    "offsite": "none"
  },
  {
    "name": "Ferritin",
    "tube": "gold",
    "aliases": [
      "ferritin"
    ],
    "offsite": "none"
  },
  {
    "name": "Vitamin B12",
    "tube": "gold",
    "aliases": [
      "B12",
      "vitamin B12",
      "cobalamin"
    ],
    "offsite": "none"
  },
  {
    "name": "Folate",
    "tube": "gold",
    "aliases": [
      "folate",
      "folic acid"
    ],
    "offsite": "none"
  },
  {
    "name": "Vitamin D",
    "tube": "gold",
    "aliases": [
      "vitamin D",
      "25-OH vitamin D",
      "25 OH"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Beta-hCG",
    "tube": "gold",
    "aliases": [
      "beta hcg",
      "bhcg",
      "hcg",
      "pregnancy test",
      "quantitative hcg"
    ],
    "offsite": "none"
  },
  {
    "name": "Troponin",
    "tube": "gold",
    "aliases": [
      "troponin",
      "trop",
      "troponin I",
      "troponin T",
      "hs-troponin"
    ],
    "offsite": "none"
  },
  {
    "name": "BNP / NT-proBNP",
    "tube": "gold",
    "aliases": [
      "BNP",
      "NT-proBNP",
      "nt pro bnp",
      "natriuretic peptide"
    ],
    "offsite": "none"
  },
  {
    "name": "Procalcitonin",
    "tube": "gold",
    "aliases": [
      "procalcitonin",
      "PCT"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Immunoglobulins",
    "tube": "gold",
    "aliases": [
      "immunoglobulins",
      "IgG",
      "IgA",
      "IgM",
      "IgE"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Complement (C3/C4)",
    "tube": "gold",
    "aliases": [
      "complement",
      "C3",
      "C4"
    ],
    "offsite": "maybe"
  },
  {
    "name": "ANA",
    "tube": "gold",
    "aliases": [
      "ANA",
      "antinuclear antibody"
    ],
    "offsite": "usually"
  },
  {
    "name": "ANCA",
    "tube": "gold",
    "aliases": [
      "ANCA"
    ],
    "offsite": "usually"
  },
  {
    "name": "dsDNA",
    "tube": "gold",
    "aliases": [
      "dsDNA",
      "anti-dsDNA",
      "double stranded DNA"
    ],
    "offsite": "usually"
  },
  {
    "name": "ENA",
    "tube": "gold",
    "aliases": [
      "ENA",
      "extractable nuclear antigen"
    ],
    "offsite": "usually"
  },
  {
    "name": "Rheumatoid Factor",
    "tube": "gold",
    "aliases": [
      "rheumatoid factor",
      "RF"
    ],
    "offsite": "none"
  },
  {
    "name": "Anti-CCP",
    "tube": "gold",
    "aliases": [
      "anti-CCP",
      "CCP"
    ],
    "offsite": "usually"
  },
  {
    "name": "Digoxin",
    "tube": "gold",
    "aliases": [
      "digoxin",
      "dig level"
    ],
    "offsite": "none"
  },
  {
    "name": "Phenytoin",
    "tube": "gold",
    "aliases": [
      "phenytoin",
      "dilantin"
    ],
    "offsite": "none"
  },
  {
    "name": "Valproate",
    "tube": "gold",
    "aliases": [
      "valproate",
      "sodium valproate",
      "epilim"
    ],
    "offsite": "none"
  },
  {
    "name": "Carbamazepine",
    "tube": "gold",
    "aliases": [
      "carbamazepine",
      "tegretol"
    ],
    "offsite": "none"
  },
  {
    "name": "Lithium",
    "tube": "gold",
    "aliases": [
      "lithium",
      "lithium level"
    ],
    "offsite": "none"
  },
  {
    "name": "Vancomycin",
    "tube": "gold",
    "aliases": [
      "vancomycin",
      "vanc level"
    ],
    "offsite": "none"
  },
  {
    "name": "Gentamicin",
    "tube": "gold",
    "aliases": [
      "gentamicin",
      "gent level"
    ],
    "offsite": "none"
  },
  {
    "name": "Paracetamol",
    "tube": "gold",
    "aliases": [
      "paracetamol",
      "acetaminophen",
      "panadol level"
    ],
    "offsite": "none"
  },
  {
    "name": "Cortisol",
    "tube": "gold",
    "aliases": [
      "cortisol"
    ],
    "offsite": "none"
  },
  {
    "name": "Testosterone",
    "tube": "gold",
    "aliases": [
      "testosterone"
    ],
    "offsite": "maybe"
  },
  {
    "name": "Oestradiol",
    "tube": "gold",
    "aliases": [
      "oestradiol",
      "estradiol"
    ],
    "offsite": "none"
  },
  {
    "name": "Progesterone",
    "tube": "gold",
    "aliases": [
      "progesterone"
    ],
    "offsite": "none"
  },
  {
    "name": "Prolactin",
    "tube": "gold",
    "aliases": [
      "prolactin"
    ],
    "offsite": "none"
  },
  {
    "name": "FSH",
    "tube": "gold",
    "aliases": [
      "FSH",
      "follicle stimulating hormone"
    ],
    "offsite": "none"
  },
  {
    "name": "LH",
    "tube": "gold",
    "aliases": [
      "LH",
      "luteinising hormone"
    ],
    "offsite": "none"
  },
  {
    "name": "Insulin",
    "tube": "gold",
    "aliases": [
      "insulin"
    ],
    "offsite": "usually"
  },
  {
    "name": "C-Peptide",
    "tube": "gold",
    "aliases": [
      "c-peptide",
      "c peptide"
    ],
    "offsite": "usually"
  },
  {
    "name": "PSA",
    "tube": "gold",
    "aliases": [
      "PSA",
      "prostate specific antigen"
    ],
    "offsite": "none"
  },
  {
    "name": "CEA",
    "tube": "gold",
    "aliases": [
      "CEA",
      "carcinoembryonic antigen"
    ],
    "offsite": "none"
  },
  {
    "name": "CA-125",
    "tube": "gold",
    "aliases": [
      "CA 125",
      "CA-125",
      "ca125"
    ],
    "offsite": "none"
  },
  {
    "name": "AFP",
    "tube": "gold",
    "aliases": [
      "AFP",
      "alpha fetoprotein"
    ],
    "offsite": "none"
  },
  {
    "name": "Coeliac Serology",
    "tube": "gold",
    "aliases": [
      "coeliac",
      "celiac",
      "tTG",
      "gliadin",
      "coeliac serology"
    ],
    "offsite": "maybe"
  },
  {
    "name": "HIV Serology",
    "tube": "gold",
    "aliases": [
      "HIV",
      "hiv serology"
    ],
    "offsite": "none"
  },
  {
    "name": "Hepatitis Serology",
    "tube": "gold",
    "aliases": [
      "hepatitis",
      "hep B",
      "hep C",
      "HBsAg",
      "HCV"
    ],
    "offsite": "none"
  },
  {
    "name": "Syphilis Serology",
    "tube": "gold",
    "aliases": [
      "syphilis",
      "RPR",
      "TPHA"
    ],
    "offsite": "none"
  },
  {
    "name": "EBV Serology",
    "tube": "gold",
    "aliases": [
      "EBV",
      "epstein barr",
      "monospot"
    ],
    "offsite": "none"
  },
  {
    "name": "CMV Serology",
    "tube": "gold",
    "aliases": [
      "CMV",
      "cytomegalovirus"
    ],
    "offsite": "none"
  },
  {
    "name": "Protein Electrophoresis",
    "tube": "gold",
    "aliases": [
      "SPEP",
      "protein electrophoresis",
      "EPP",
      "protein studies"
    ],
    "offsite": "usually"
  },
  {
    "name": "Albumin",
    "tube": "gold",
    "aliases": [
      "albumin"
    ],
    "offsite": "none"
  }
];
const LABS = [
  {
    "id": "ICPMR",
    "name": "ICPMR Westmead (statewide reference)",
    "state": "NSW"
  }
];
const STATES = [
  {
    "id": "NSW",
    "name": "New South Wales",
    "catalogueHome": "https://catalogue.pathology.health.nsw.gov.au/home",
    "catalogueSearch": "https://catalogue.pathology.health.nsw.gov.au/search?searchValue="
  }
];
const SITES = [
  {
    "id": "default",
    "name": "Generic (NSW default)",
    "state": "NSW"
  },
  {
    "id": "nepean",
    "name": "Nepean Hospital",
    "state": "NSW"
  },
  {
    "id": "westmead",
    "name": "Westmead Hospital",
    "state": "NSW"
  }
];
const OVERRIDES = [
  {
    "scope": "site",
    "scopeId": "nepean",
    "test": "Group & Hold",
    "field": "quantity",
    "value": "2"
  }
];
